import type { CSSProperties } from "react";
import { POS_COLOR, Pos } from "@/lib/draftLogic";

export const fontImport = `
  @import url('https://fonts.googleapis.com/css2?family=Oswald:wght@400;500;600;700&family=IBM+Plex+Mono:wght@400;500;600&family=Inter:wght@400;500;600&display=swap');
`;

export function chipActive(pos: string): CSSProperties {
  const bg = pos === "ALL" ? "#EDEEF0" : pos === "LIKED" ? "#4CAF6B" : POS_COLOR[pos as Pos];
  return {
    background: bg,
    borderColor: bg,
    color: "#14171C",
    fontWeight: 600,
  };
}

export const styles: Record<string, CSSProperties> = {
  app: {
    fontFamily: "'Inter', -apple-system, sans-serif",
    background: "#14171C",
    color: "#EDEEF0",
    minHeight: "100vh",
    padding: "16px 14px 40px",
    maxWidth: 720,
    margin: "0 auto",
    boxSizing: "border-box",
  },
  loadingScreen: {
    background: "#14171C",
    color: "#8B92A0",
    minHeight: "100vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontFamily: "'Inter', sans-serif",
  },
  loadingText: { fontSize: 14 },
  iconBtn: {
    background: "#1C2128",
    border: "1px solid #2A2F38",
    color: "#EDEEF0",
    borderRadius: 8,
    width: 38,
    height: 38,
    fontSize: 16,
    cursor: "pointer",
  },
  panel: {
    background: "#1C2128",
    border: "1px solid #2A2F38",
    borderRadius: 10,
    padding: 14,
    marginBottom: 14,
  },
  panelTitle: {
    fontFamily: "'Oswald', sans-serif",
    fontSize: 14,
    fontWeight: 500,
    marginBottom: 10,
    color: "#8B92A0",
    textTransform: "uppercase",
    letterSpacing: "0.05em",
  },
  settingsGrid: { display: "flex", gap: 10, marginBottom: 12 },
  settingLabel: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    fontSize: 11,
    color: "#8B92A0",
    flex: 1,
  },
  input: {
    background: "#14171C",
    border: "1px solid #2A2F38",
    borderRadius: 6,
    color: "#EDEEF0",
    padding: "8px 10px",
    fontSize: 14,
    fontFamily: "'IBM Plex Mono', monospace",
    width: "100%",
    boxSizing: "border-box",
  },
  select: {
    background: "#14171C",
    border: "1px solid #2A2F38",
    borderRadius: 6,
    color: "#EDEEF0",
    padding: "8px 10px",
    fontSize: 14,
  },
  dangerBtn: {
    background: "transparent",
    border: "1px solid #E1524B",
    color: "#E1524B",
    borderRadius: 6,
    padding: "8px 12px",
    fontSize: 13,
    cursor: "pointer",
    width: "100%",
  },
  tabs: {
    display: "flex",
    gap: 6,
    marginBottom: 12,
    borderBottom: "1px solid #2A2F38",
    overflowX: "auto",
    whiteSpace: "nowrap",
  },
  tab: {
    background: "transparent",
    border: "none",
    color: "#8B92A0",
    padding: "8px 4px",
    fontSize: 13,
    cursor: "pointer",
    borderBottom: "2px solid transparent",
    marginRight: 10,
  },
  tabActive: {
    background: "transparent",
    border: "none",
    color: "#EDEEF0",
    padding: "8px 4px",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    borderBottom: "2px solid #4CAF6B",
    marginRight: 10,
  },
  controlsRow: { display: "flex", gap: 8, marginBottom: 10 },
  searchInput: {
    flex: 1,
    background: "#1C2128",
    border: "1px solid #2A2F38",
    borderRadius: 8,
    color: "#EDEEF0",
    padding: "9px 12px",
    fontSize: 14,
  },
  smallBtn: {
    background: "#1C2128",
    border: "1px solid #2A2F38",
    color: "#EDEEF0",
    borderRadius: 8,
    padding: "9px 12px",
    fontSize: 13,
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  chipRow: { display: "flex", gap: 6, marginBottom: 10, flexWrap: "wrap" },
  chip: {
    background: "#1C2128",
    border: "1px solid #2A2F38",
    color: "#8B92A0",
    borderRadius: 999,
    padding: "5px 12px",
    fontSize: 12,
    cursor: "pointer",
  },
  sortRow: { display: "flex", alignItems: "center", gap: 6, marginBottom: 10, flexWrap: "wrap" },
  sortLabel: { fontSize: 11, color: "#8B92A0", marginRight: 2 },
  sortBtn: {
    background: "transparent",
    border: "1px solid #2A2F38",
    color: "#8B92A0",
    borderRadius: 6,
    padding: "4px 8px",
    fontSize: 11,
    cursor: "pointer",
  },
  sortBtnActive: {
    background: "#2A2F38",
    border: "1px solid #4CAF6B",
    color: "#EDEEF0",
    borderRadius: 6,
    padding: "4px 8px",
    fontSize: 11,
    cursor: "pointer",
  },
  list: { display: "flex", flexDirection: "column", gap: 6 },
  emptyState: {
    color: "#8B92A0",
    fontSize: 13,
    padding: "20px 10px",
    textAlign: "center",
    lineHeight: 1.5,
  },
  playerCard: {
    background: "#1C2128",
    border: "1px solid #2A2F38",
    borderRadius: 10,
    overflow: "hidden",
  },
  playerRowTop: {
    display: "flex",
    alignItems: "center",
    padding: "10px 12px",
    gap: 10,
    cursor: "pointer",
  },
  posTag: {
    fontFamily: "'IBM Plex Mono', monospace",
    fontSize: 10,
    fontWeight: 700,
    color: "#14171C",
    borderRadius: 5,
    padding: "3px 6px",
    minWidth: 28,
    textAlign: "center",
  },
  playerInfo: { flex: 1, minWidth: 0 },
  playerName: {
    fontSize: 14,
    fontWeight: 500,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  playerMeta: { fontSize: 11, color: "#8B92A0", marginTop: 1 },
  priceCol: { textAlign: "right", flexShrink: 0 },
  targetPrice: { fontFamily: "'IBM Plex Mono', monospace", fontSize: 12, color: "#8B92A0" },
  livePrice: { fontFamily: "'IBM Plex Mono', monospace", fontSize: 14, fontWeight: 600 },
  draftedTag: { fontFamily: "'IBM Plex Mono', monospace", fontSize: 11, color: "#8B92A0" },
  expandPanel: {
    padding: "0 12px 12px",
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  row: { display: "flex", gap: 8, alignItems: "center", marginBottom: 8 },
  mineLabel: {
    display: "flex",
    alignItems: "center",
    gap: 5,
    fontSize: 12,
    color: "#8B92A0",
    whiteSpace: "nowrap",
  },
  primaryBtn: {
    background: "#4CAF6B",
    border: "none",
    color: "#0E1310",
    borderRadius: 6,
    padding: "9px 14px",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
  },
  keeperRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    background: "#1C2128",
    border: "1px solid #2A2F38",
    borderRadius: 10,
    padding: "10px 12px",
  },
  keeperName: { flex: 1, fontSize: 13 },
  mineTag: {
    fontFamily: "'IBM Plex Mono', monospace",
    fontSize: 9,
    color: "#4CAF6B",
    marginLeft: 6,
  },
  keeperCost: { fontFamily: "'IBM Plex Mono', monospace", fontSize: 13, fontWeight: 600 },
  removeBtn: {
    background: "transparent",
    border: "none",
    color: "#8B92A0",
    fontSize: 14,
    cursor: "pointer",
    padding: 4,
  },
  myTeamStats: {
    display: "flex",
    gap: 14,
    fontSize: 12,
    color: "#8B92A0",
    fontFamily: "'IBM Plex Mono', monospace",
  },
  footer: {
    textAlign: "center",
    fontSize: 10,
    color: "#4A5160",
    marginTop: 20,
  },
  strategyCard: {
    background: "#1C2128",
    border: "1px solid #2A2F38",
    borderRadius: 10,
    padding: "10px 12px",
  },
  strategyHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    cursor: "pointer",
    marginBottom: 8,
  },
  allocRow: { display: "flex", gap: 8, flexWrap: "wrap" },
  allocChip: {
    fontSize: 11,
    background: "#14171C",
    border: "1px solid #2A2F38",
    borderRadius: 6,
    padding: "4px 8px",
    fontFamily: "'IBM Plex Mono', monospace",
  },
  allocDollar: { color: "#8B92A0" },
  tableWrap: {
    overflowX: "auto",
    border: "1px solid #2A2F38",
    borderRadius: 10,
    WebkitOverflowScrolling: "touch",
  },
  table: {
    borderCollapse: "collapse",
    width: "100%",
    fontSize: 12,
  },
  th: {
    position: "sticky",
    top: 0,
    background: "#1C2128",
    color: "#8B92A0",
    fontWeight: 600,
    fontSize: 10,
    textTransform: "uppercase",
    letterSpacing: "0.03em",
    padding: "8px 6px",
    borderBottom: "1px solid #2A2F38",
    textAlign: "center",
    whiteSpace: "nowrap",
  },
  thSticky: {
    position: "sticky",
    left: 0,
    zIndex: 3,
    background: "#1C2128",
    minWidth: 38,
    maxWidth: 38,
    padding: "8px 2px",
  },
  thSticky2: {
    position: "sticky",
    left: 38,
    zIndex: 2,
    background: "#1C2128",
    minWidth: 120,
    width: "99%",
    padding: "8px 4px",
    textAlign: "left",
    boxShadow: "2px 0 0 #2A2F38",
  },
  // When the board's drag handle is visible, the first sticky column widens;
  // downstream pinned columns (Plan, Player) compute their own "left" offset
  // dynamically in DraftTool to match. Apply on top of th/tdSticky.
  stickyDragCol1: { minWidth: 62, maxWidth: 62 },
  td: {
    padding: "6px 6px",
    borderBottom: "1px solid #20242C",
    whiteSpace: "nowrap",
    background: "#171A20",
    textAlign: "center",
  },
  tdSticky: {
    position: "sticky",
    left: 0,
    zIndex: 2,
    background: "#171A20",
    minWidth: 38,
    maxWidth: 38,
    padding: "6px 2px",
    textAlign: "center",
  },
  tdSticky2: {
    position: "sticky",
    left: 38,
    zIndex: 1,
    background: "#171A20",
    minWidth: 120,
    // Take the table's leftover width so the board fills the screen instead of
    // leaving blank space on the right; the numeric columns stay content-sized.
    width: "99%",
    padding: "6px 4px",
    textAlign: "left",
    boxShadow: "2px 0 0 #20242C",
  },
  tdMono: { fontFamily: "'IBM Plex Mono', monospace", fontSize: 12, color: "#EDEEF0" },
  tdPlayerName: {
    fontSize: 12.5,
    fontWeight: 500,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    maxWidth: 320,
    textAlign: "left",
  },
  tdPlayerMeta: { fontSize: 10, color: "#8B92A0", marginTop: 1, textAlign: "left" },
  posTagSm: {
    fontFamily: "'IBM Plex Mono', monospace",
    fontSize: 9,
    fontWeight: 700,
    color: "#14171C",
    borderRadius: 4,
    padding: "2px 5px",
  },
  tierBadge: {
    fontSize: 9,
    color: "#8B92A0",
    marginLeft: 4,
  },
  tierDot: {
    display: "inline-block",
    width: 7,
    height: 7,
    borderRadius: "50%",
  },
  tierDivider: {
    height: 16,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    touchAction: "none",
    userSelect: "none",
  },
  tierDividerHandle: {
    fontSize: 9,
    letterSpacing: "0.04em",
    color: "#171A20",
    fontWeight: 700,
  },
  cellInput: {
    width: 42,
    background: "#14171C",
    border: "1px solid #2A2F38",
    borderRadius: 5,
    color: "#EDEEF0",
    padding: "5px 4px",
    fontSize: 12,
    fontFamily: "'IBM Plex Mono', monospace",
    textAlign: "center",
  },
  cellSelect: {
    width: 64,
    border: "none",
    borderRadius: 5,
    padding: "5px 2px",
    fontSize: 10,
    fontWeight: 700,
    fontFamily: "'IBM Plex Mono', monospace",
    textAlign: "center",
  },
  statusSelect: {
    width: 74,
    background: "#14171C",
    border: "1px solid #2A2F38",
    borderRadius: 5,
    color: "#EDEEF0",
    padding: "5px 2px",
    fontSize: 10,
    fontWeight: 600,
    textAlign: "center",
  },
  endgameBanner: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    background: "rgba(232, 163, 61, 0.12)",
    border: "1px solid #E8A33D",
    borderRadius: 10,
    padding: "10px 12px",
    fontSize: 12,
    color: "#EDEEF0",
    marginBottom: 12,
  },
  endgameBannerActive: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    background: "rgba(76, 175, 107, 0.12)",
    border: "1px solid #4CAF6B",
    borderRadius: 10,
    padding: "10px 12px",
    fontSize: 12,
    color: "#EDEEF0",
    marginBottom: 12,
  },
  compPrice: {
    color: "#8B92A0",
    fontFamily: "'IBM Plex Mono', monospace",
  },
};
